name: "gh-repo-shipper"

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    name: "gh-repo-shipper"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET: ${{ secrets.S3_REPO_BUCKET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tar
        run: |
          touch repo.tar.gz
          tar --exclude=repo.tar.gz -czvf repo.tar.gz ./

      - name: S3
        run: |
          aws s3 cp repo.tar.gz s3://$BUCKET/${{ github.event.repository.name }}/repo.tar.gz
